In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/NF-UQ-NIDS.csv')

df.head()

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,OUT_BYTES,IN_PKTS,OUT_PKTS,TCP_FLAGS,FLOW_DURATION_MILLISECONDS,Label,Attack,Dataset
0,149.171.126.0,62073,59.166.0.5,56082,6,0.0,9672,416,11,8,25,15,0,Benign,NF-UNSW-NB15
1,149.171.126.2,32284,59.166.0.5,1526,6,0.0,1776,104,6,2,25,0,0,Benign,NF-UNSW-NB15
2,149.171.126.0,21,59.166.0.1,21971,6,1.0,1842,1236,26,22,25,1111,0,Benign,NF-UNSW-NB15
3,59.166.0.1,23800,149.171.126.0,46893,6,0.0,528,8824,10,12,27,124,0,Benign,NF-UNSW-NB15
4,59.166.0.5,63062,149.171.126.2,21,6,1.0,1786,2340,32,34,25,1459,0,Benign,NF-UNSW-NB15

In [14]:
df[df.Attack != 'Benign'].sample(n=5, random_state=1)

,IPV4_SRC_ADDR,L4_SRC_PORT,IPV4_DST_ADDR,L4_DST_PORT,PROTOCOL,L7_PROTO,IN_BYTES,OUT_BYTES,IN_PKTS,OUT_PKTS,TCP_FLAGS,FLOW_DURATION_MILLISECONDS,Label,Attack,Dataset
4626436,172.31.69.6,56156,18.219.211.138,8080,6,131.7,538,341,5,5,219,4294951,1,Bot,NF-CSE-CIC-IDS2018
11308300,13.58.98.64,37354,172.31.69.25,22,6,0.0,3116,0,23,0,27,0,1,Brute Force,NF-CSE-CIC-IDS2018
1824697,192.168.1.33,52942,192.168.1.195,80,6,7.0,458,2203,5,6,27,278,1,injection,NF-ToN-IoT
2847270,192.168.1.30,44534,192.168.1.184,443,6,91.0,112,60,2,1,18,0,1,DDoS,NF-ToN-IoT
11744721,192.168.100.149,40629,192.168.100.3,2111,6,0.0,44,40,1,1,22,4294966,1,Reconnaissance,NF-BoT-IoT

In [15]:
df.isnull().sum()

IPV4_SRC_ADDR                 0
L4_SRC_PORT                   0
IPV4_DST_ADDR                 0
L4_DST_PORT                   0
PROTOCOL                      0
L7_PROTO                      0
IN_BYTES                      0
OUT_BYTES                     0
IN_PKTS                       0
OUT_PKTS                      0
TCP_FLAGS                     0
FLOW_DURATION_MILLISECONDS    0
Label                         0
Attack                        0
Dataset                       0
dtype: int64